export enum FsCollectionName {
  Abilities = 'Abilities',
  AbilityTypes = 'AbilityTypes',
  CharacterTags = 'CharacterTags',
  CharacterTypes = 'CharacterTypes',
  Characters = 'Characters',
  Facilities = 'Facilities',
  FacilityTypes = 'FacilityTypes',
  GeographTypes = 'GeographTypes',
  Illustrators = 'Illustrators',
  Regions = 'Regions',
  VoiceActors = 'VoiceActors',
  Weapons = 'Weapons',
  WeaponTypes = 'WeaponTypes',
}
